export const apiConfig = {
  aid: 0,
  vpot: false,
  fw: "N/A",
  plugin: "N/A",
  ip: "N/A",
  pre: 0,
  addcfg: 0,
  adcsum: 0,
  vinputs: false
};

export const apiSpdifout = { spdifleft: "0x00000000", spdifright: "0x00000001" };

export const apiAllinputs = {
  num: 8,
  in0: "0x00000000",
  in1: "0x00000001",
  in2: "0x00000000",
  in3: "0x00000001",
  in4: "0x00000000",
  in5: "0x00000001",
  in6: "0x00000006",
  in7: "0x00000007"
};

export const apiAllbyp = {
  byp: [
    { name: "hp0", val: 0 },
    { name: "hp1", val: 0 },
    { name: "hp2", val: 0 },
    { name: "hp3", val: 0 },
    { name: "hp4", val: 0 },
    { name: "hp5", val: 0 },
    { name: "hp6", val: 0 },
    { name: "hp7", val: 0 },
    { name: "ls0", val: 0 },
    { name: "ls1", val: 0 },
    { name: "ls2", val: 0 },
    { name: "ls3", val: 0 },
    { name: "ls4", val: 0 },
    { name: "ls5", val: 0 },
    { name: "ls6", val: 0 },
    { name: "ls7", val: 0 },
    { name: "peqbank0", val: 0 },
    { name: "peqbank1", val: 0 },
    { name: "peqbank2", val: 0 },
    { name: "peqbank3", val: 0 },
    { name: "peqbank4", val: 0 },
    { name: "peqbank5", val: 0 },
    { name: "peqbank6", val: 0 },
    { name: "peqbank7", val: 0 },
    { name: "hs0", val: 0 },
    { name: "hs1", val: 0 },
    { name: "hs2", val: 0 },
    { name: "hs3", val: 0 },
    { name: "hs4", val: 0 },
    { name: "hs5", val: 0 },
    { name: "hs6", val: 0 },
    { name: "hs7", val: 0 },
    { name: "lp0", val: 0 },
    { name: "lp1", val: 0 },
    { name: "lp2", val: 0 },
    { name: "lp3", val: 0 },
    { name: "lp4", val: 0 },
    { name: "lp5", val: 0 },
    { name: "lp6", val: 0 },
    { name: "lp7", val: 0 },
    { name: "ph0", val: 0 },
    { name: "ph1", val: 0 },
    { name: "ph2", val: 0 },
    { name: "ph3", val: 0 },
    { name: "ph4", val: 0 },
    { name: "ph5", val: 0 },
    { name: "ph6", val: 0 },
    { name: "ph7", val: 0 },
    { name: "dly0", val: 0 },
    { name: "dly1", val: 0 },
    { name: "dly2", val: 0 },
    { name: "dly3", val: 0 },
    { name: "dly4", val: 0 },
    { name: "dly5", val: 0 },
    { name: "dly6", val: 0 },
    { name: "dly7", val: 0 },
    { name: "gn0", val: 0 },
    { name: "gn1", val: 0 },
    { name: "gn2", val: 0 },
    { name: "gn3", val: 0 },
    { name: "gn4", val: 0 },
    { name: "gn5", val: 0 },
    { name: "gn6", val: 0 },
    { name: "gn7", val: 0 }
  ]
};

export const apiAllfc = {
  fc: [
    { name: "hp0", val: "HP<br><h4>0 Hz</h4>" },
    { name: "hp1", val: "HP<br><h4>0 Hz</h4>" },
    { name: "hp2", val: "HP<br><h4>0 Hz</h4>" },
    { name: "hp3", val: "HP<br><h4>0 Hz</h4>" },
    { name: "hp4", val: "HP<br><h4>0 Hz</h4>" },
    { name: "hp5", val: "HP<br><h4>0 Hz</h4>" },
    { name: "hp6", val: "HP<br><h4>0 Hz</h4>" },
    { name: "hp7", val: "HP<br><h4>0 Hz</h4>" },
    { name: "ls0", val: "LShlv<br><h4>0.0 dB</h4>" },
    { name: "ls1", val: "LShlv<br><h4>0.0 dB</h4>" },
    { name: "ls2", val: "LShlv<br><h4>0.0 dB</h4>" },
    { name: "ls3", val: "LShlv<br><h4>0.0 dB</h4>" },
    { name: "ls4", val: "LShlv<br><h4>0 dB</h4>" },
    { name: "ls5", val: "LShlv<br><h4>0 dB</h4>" },
    { name: "ls6", val: "LShlv<br><h4>0.0 dB</h4>" },
    { name: "ls7", val: "LShlv<br><h4>0.0 dB</h4>" },
    { name: "hs0", val: "HShlv<br><h4>0.0 dB</h4>" },
    { name: "hs1", val: "HShlv<br><h4>0.0 dB</h4>" },
    { name: "hs2", val: "HShlv<br><h4>0.0 dB</h4>" },
    { name: "hs3", val: "HShlv<br><h4>0.0 dB</h4>" },
    { name: "hs4", val: "HShlv<br><h4>0.0 dB</h4>" },
    { name: "hs5", val: "HShlv<br><h4>0.0 dB</h4>" },
    { name: "hs6", val: "HShlv<br><h4>0.0 dB</h4>" },
    { name: "hs7", val: "HShlv<br><h4>0.0 dB</h4>" },
    { name: "lp0", val: "LP<br><h4>0 Hz</h4>" },
    { name: "lp1", val: "LP<br><h4>0 Hz</h4>" },
    { name: "lp2", val: "LP<br><h4>0 Hz</h4>" },
    { name: "lp3", val: "LP<br><h4>0 Hz</h4>" },
    { name: "lp4", val: "LP<br><h4>0 Hz</h4>" },
    { name: "lp5", val: "LP<br><h4>0 Hz</h4>" },
    { name: "lp6", val: "LP<br><h4>0 Hz</h4>" },
    { name: "lp7", val: "LP<br><h4>0 Hz</h4>" },
    { name: "ph0", val: "Phase<br><h4>0 Hz</h4>" },
    { name: "ph1", val: "Phase<br><h4>0 Hz</h4>" },
    { name: "ph2", val: "Phase<br><h4>0 Hz</h4>" },
    { name: "ph3", val: "Phase<br><h4>0 Hz</h4>" },
    { name: "ph4", val: "Phase<br><h4>0 Hz</h4>" },
    { name: "ph5", val: "Phase<br><h4>0 Hz</h4>" },
    { name: "ph6", val: "Phase<br><h4>0 kHz</h4>" },
    { name: "ph7", val: "Phase<br><h4>0 Hz</h4>" },
    { name: "dly0", val: "Delay<br><h4>0.0 ms</h4>" },
    { name: "dly1", val: "Delay<br><h4>0.0 ms</h4>" },
    { name: "dly2", val: "Delay<br><h4>0.0 ms</h4>" },
    { name: "dly3", val: "Delay<br><h4>0.0 ms</h4>" },
    { name: "dly4", val: "Delay<br><h4>0.0 ms</h4>" },
    { name: "dly5", val: "Delay<br><h4>0.0 ms</h4>" },
    { name: "dly6", val: "Delay<br><h4>0.0 ms</h4>" },
    { name: "dly7", val: "Delay<br><h4>0.0 ms</h4>" },
    { name: "gn0", val: "Gain<br><h4>0.0 dB</h4>" },
    { name: "gn1", val: "Gain<br><h4>0.0 dB</h4>" },
    { name: "gn2", val: "Gain<br><h4>0.0 dB</h4>" },
    { name: "gn3", val: "Gain<br><h4>0.0 dB</h4>" },
    { name: "gn4", val: "Gain<br><h4>0.0 dB</h4>" },
    { name: "gn5", val: "Gain<br><h4>0.0 dB</h4>" },
    { name: "gn6", val: "Gain<br><h4>0.0 dB</h4>" },
    { name: "gn7", val: "Gain<br><h4>0.0 dB</h4>" }
  ]
};

export const apiMvol = { vol: -55 };

export const apiAllnames = {
  inputs: [
    "Channel 1",
    "Channel 2",
    "Channel 3",
    "Channel 4",
    "Channel 5",
    "Channel 6",
    "Channel 7",
    "Channel 8"
  ],
  outputs: ["Out 1", "Out 2", "Out 3", "Out 4", "Out 5", "Out 6", "Out 7", "Out 8"],
  presets: ["Preset A", "Preset B", "Preset C", "Preset D"],
  sources: [],
  selvinput: 0
};

export const apiWificonfig = { apname: "AP-freeDSP-Aurora", ssid: "N/A" };
